config/routes.rb
Pkproject::Application.routes.draw do
  
  devise_for :users

  resources :bricks do 
    shallow do
      resources :mortars
    end
  end
  
  resources :states, :categories
  
  root :to => 'pages#{home}'

end

app/models/brick.rb
class Brick < ActiveRecord::Base
  has_many :mortars
  
  has_many :categorizations
  has_many :categories, :through => :categorizations
  
  has_many :relationships, :class_name => "Relationship", :foreign_key => "source_id"
  has_many :targets, :through => :relationships
  
  def sources
    relationships = Relationship.by_target(self.id)
    sources = []
    relationships.each do |relation|
      sources << Brick.find(relation.source_id)
    end
    return sources
  end
  
  def sources_and_targets
    self.sources.zip(self.targets)
  end
  
  def self.search(search)
    if search
      where("bricks.name LIKE ?", "%#{search}")
    else
      scoped
    end
  end
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :category
  belongs_to :brick
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations
  has_many :bricks, :through => :categorizations
end

app/models/gender.rb
class Gender < ActiveRecord::Base
  has_many :mortars
end

app/models/mortar.rb
class Mortar < ActiveRecord::Base
  belongs_to :brick
  belongs_to :species
  belongs_to :gender
  belongs_to :state
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  
  belongs_to :source, :class_name => "Brick"
  belongs_to :target, :class_name => "Brick"
    
  def self.by_target(target)
    where("relationships.target_id = ?", target)
  end
end

app/models/species.rb
class Species < ActiveRecord::Base
  has_many :mortars
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :mortars
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bricks_controller.rb
class BricksController < InheritedResources::Base
  
  respond_to :html
  respond_to :js, :only => :index
  
  def index
    @bricks = Brick.search(params[:search]).order("name").page(params[:page])
  end
  
  protected
  
  def collection
    @bricks ||= end_of_association_chain.order("name").page(params[:page])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base
  
  
  protected
  
  def collection
    @categories ||= end_of_association_chain.order("name").page(params[:page])
  end
end

app/controllers/mortars_controller.rb
class MortarsController < InheritedResources::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    
  end
end

app/controllers/states_controller.rb
class StatesController < InheritedResources::Base
  
  
  protected
  
  def collection
    @states ||= end_of_association_chain.order("name").page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def render_target_and_sources(resource)
    render_targets(resource)
    render_sources(resource)
  end
  
  private
  
  def render_targets(resource)
    render 'shared/relationships_table', :resources => resource.targets
  end
  
  def render_sources(resource)
    render 'shared/relationships_table', :resources => resource.sources
  end
end

app/helpers/bricks_helper.rb
module BricksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/mortars_helper.rb
module MortarsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/bricks/_brick.html.haml
%h3= link_to brick.name, brick_path(brick)

- unless brick.description.blank?
  %p= brick.description

app/views/bricks/_table_data.html.haml
%table#brick_data
  %thead
    %tr.top_header
      %th{:colspan => "9"}= @brick.name
    %tr.middle_header
      %th Gender
      %th Species
      %th.state State
      %th{:colspan => "5"} Values
      %th.notes Notes
    %tr.bottom_header
      %th
      %th
      %th.state
      %th Min
      %th Max
      %th Mean
      %th Std Dev
      %th Units
      %th.notes
  
  %tbody
  - @brick.mortars.each do |mortar|
    %tr
      %td= mortar.species.name
      %td= mortar.gender.name
      %td.state= mortar.state.name
      %td= mortar.min
      %td= mortar.max
      %td= mortar.mean
      %td= mortar.stdev
      %td pg/mL
      %td.notes= link_to 'Read more >>', mortar_path(mortar)

app/views/bricks/index.html.haml
= form_tag bricks_path, :method => 'get', :id => 'bricks_search' do
  %p
    = text_field_tag :search, params[:search]
    = submit_tag 'Search', :name => nil

#bricks
  = render 'shared/index', :resources => @bricks

app/views/bricks/show.html.haml
- content_for :header do
  = link_to 'All Bricks', bricks_path 
  &gt;
  = @brick.name

- unless @brick.description.blank?  
  .description
    = @brick.description
  
= render 'table_data'

%br/

= render 'shared/relationships_table', :resources => @brick.sources
= render 'shared/relationships_table', :resources => @brick.targets

app/views/categories/index.html.haml
= render 'shared/index', :resources => @categories

app/views/mortars/_table_data.html.haml
%table#mortar_data
  %thead
    %tr.top_header
      %th{:colspan => "8"}= @mortar.brick.name
    %tr.middle_header
      %th Gender
      %th Species
      %th.state State
      %th{:colspan => "5"} Values
    %tr.bottom_header
      %th
      %th
      %th.state
      %th Min
      %th Max
      %th Mean
      %th Std Dev
      %th Units
  
  %tbody
    %tr
      %td= @mortar.species.name
      %td= @mortar.gender.name
      %td.state= @mortar.state.name
      %td= @mortar.min
      %td= @mortar.max
      %td= @mortar.mean
      %td= @mortar.stdev
      %td pg/mL

app/views/mortars/show.html.haml
- content_for :header do
  = link_to 'All Bricks', bricks_path 
  &gt; 
  = link_to @mortar.brick.name, brick_path(@mortar.brick)
  &gt; Mortar
  
= render 'table_data'

%br/

= render 'shared/relationships_table'

app/views/states/index.html.haml
= render 'shared/index', :resources => @states