config/routes.rb
Pkproject::Application.routes.draw do
  
  devise_for :users

  resources :bricks do 
    shallow do
      resources :mortars
    end
  end
  
  resources :states, :categories
  
  root :to => 'pages#{home}'

end

app/models/brick.rb
class Brick < ActiveRecord::Base
  has_many :mortars
  
  has_many :categorizations
  has_many :categories, :through => :categorizations
  
  has_many :relationships, :class_name => "Relationship", :foreign_key => "source_id"
  has_many :targets, :through => :relationships
  
  def sources
    relationships = Relationship.by_target(self.id)
    sources = []
    relationships.each do |relation|
      sources << Brick.find(relation.source_id)
    end
    return sources
  end
  
  def sources_and_targets
    self.sources.zip(self.targets)
  end
  
  def self.search(search)
    if search
      where("bricks.name LIKE ?", "%#{search}")
    else
      scoped
    end
  end
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :category
  belongs_to :brick
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations
  has_many :bricks, :through => :categorizations
end

app/models/gender.rb
class Gender < ActiveRecord::Base
  has_many :mortars
end

app/models/mortar.rb
class Mortar < ActiveRecord::Base
  belongs_to :brick
  belongs_to :species
  belongs_to :gender
  belongs_to :state
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  
  belongs_to :source, :class_name => "Brick"
  belongs_to :target, :class_name => "Brick"
    
  def self.by_target(target)
    where("relationships.target_id = ?", target)
  end
end

app/models/species.rb
class Species < ActiveRecord::Base
  has_many :mortars
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :mortars
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/bricks_controller.rb
class BricksController < InheritedResources::Base
  
  respond_to :html
  respond_to :js, :only => :index
  
  def index
    @bricks = Brick.search(params[:search]).order("name").page(params[:page])
  end
  
  protected
  
  def collection
    @bricks ||= end_of_association_chain.order("name").page(params[:page])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base
  
  
  protected
  
  def collection
    @categories ||= end_of_association_chain.order("name").page(params[:page])
  end
end

app/controllers/mortars_controller.rb
class MortarsController < InheritedResources::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    
  end
end

app/controllers/states_controller.rb
class StatesController < InheritedResources::Base
  
  
  protected
  
  def collection
    @states ||= end_of_association_chain.order("name").page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def render_target_and_sources(resource)
    render_targets(resource)
    render_sources(resource)
  end
  
  private
  
  def render_targets(resource)
    render 'shared/relationships_table', :resources => resource.targets
  end
  
  def render_sources(resource)
    render 'shared/relationships_table', :resources => resource.sources
  end
end

app/helpers/bricks_helper.rb
module BricksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/mortars_helper.rb
module MortarsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/layouts/application.html.haml
!!! 1.1
%html{:xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "en", :name => "language"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "keywords"}/
    %title Home | PKProject
    = stylesheet_link_tag 'application'
    = javascript_include_tag :defaults
  %body
    #bar
    #wrapper
      #header
        %h1= link_to "pkProject", root_url
        .headerLinks
          %ul
            %li{:style => "border:none;"}
              %a{:href => "#"} About
            %li
              %a{:href => "#"} Help
            %li
              %a{:href => "#"} Contact Us
        .search
          %form#cse-search-box.searchBox{:action => "http://www.google.com/cse"}
            %input{:name => "cx", :type => "hidden", :value => "006303564329511420807:yfb1kmigwag"}/
            %input{:name => "ie", :type => "hidden", :value => "UTF-8"}/
            %input{:name => "q", :size => "20", :type => "text", :value => "Search pkProject"}/
            %input.submitButton{:name => "Submit", :style => "background-color:#eee;", :type => "submit", :value => "Submit"}/
      %hr/
      %hr/
      #topText
        %h1= yield(:header)
      %hr/
      
      #content
        = yield
      / end of content
      %hr/
      #footer
        %p ©2010 - The University of Mississippi Medical Center
        %p Supported by: NSF EPSCOR, NASA, NIH
    / end of wrapper

app/views/pages/home.html.haml
- content_for :header do
  This is what the pkProject is. A lot of confusing things about phyisiology that you would understand if you are a researcher, scientist or student at MIT. Hopefully this will be useful.

#buttons.home
  = link_to 'Bricks', bricks_path
  = link_to 'States', states_path
  = link_to 'Categories', categories_path

app/views/shared/_index.html.haml
- content_for :header do
  All 
  = resources.first.class.name.pluralize  

= paginate resources

%ul
  - resources.each do |resource|
    %li
      = link_to resource.name, resource
      - unless resource.description.blank?  
        .description
          = resource.description

app/views/shared/_relationships_table.html.haml
%table.relationship_data
  %thead
    %tr.middle_header
      %th Sources
      %th Targets
  %tbody
  
    - resources.each do |resource|
      %tr
        %td= link_to resource.name, resource